module.exports = {
  content: ['./index.html', './main.js', './scripts/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#1c1000',
        'surface-container-highest': '#343532',
        secondary: '#e9c176',
        primary: '#c8c6c5',
        'on-background': '#e4e2dd',
        'inverse-primary': '#5f5e5e',
        'on-secondary-fixed-variant': '#5d4201',
        'tertiary-fixed': '#ffddb0',
        'surface-variant': '#343532',
        'surface-tint': '#c8c6c5',
        surface: '#131411',
        'error-container': '#93000a',
        'on-tertiary-fixed': '#281800',
        'inverse-on-surface': '#30312e',
        'surface-container': '#1f201d',
        'secondary-fixed-dim': '#e9c176',
        outline: '#8e9192',
        tertiary: '#e7c08a',
        'on-secondary-fixed': '#261900',
        'surface-container-lowest': '#0e0e0c',
        'primary-container': '#121212',
        'surface-dim': '#131411',
        'on-tertiary-fixed-variant': '#5c4217',
        error: '#ffb4ab',
        'on-primary-fixed-variant': '#474646',
        'surface-container-high': '#2a2a27',
        'on-primary-fixed': '#1c1b1b',
        'outline-variant': '#444748',
        'on-secondary-container': '#dab36a',
        'surface-container-low': '#1b1c19',
        'inverse-surface': '#e4e2dd',
        'on-secondary': '#412d00',
        'on-primary': '#313030',
        'secondary-fixed': '#ffdea5',
        'primary-fixed': '#e5e2e1',
        'on-error-container': '#ffdad6',
        'on-tertiary-container': '#987848',
        'tertiary-fixed-dim': '#e7c08a',
        'secondary-container': '#604403',
        'primary-fixed-dim': '#c8c6c5',
        'on-primary-container': '#7e7d7d',
        'on-error': '#690005',
        'on-surface': '#e4e2dd',
        'surface-bright': '#393936',
        'on-surface-variant': '#c4c7c7',
        'on-tertiary': '#432c03',
        background: '#131411',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.5rem',
      },
      spacing: {
        'section-gap': '80px',
        'grid-columns': '12',
        base: '8px',
        'max-width': '1200px',
        gutter: '16px',
        'container-padding': '24px',
      },
      fontFamily: {
        'headline-md': ['Newsreader', 'serif'],
        'display-lg-mobile': ['Newsreader', 'serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Newsreader', 'serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Newsreader', 'serif'],
      },
      fontSize: {
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-md': [
          '14px',
          { lineHeight: '1', letterSpacing: '0', fontWeight: '600' },
        ],
        'display-lg': [
          '48px',
          { lineHeight: '1.1', letterSpacing: '0', fontWeight: '600' },
        ],
        'label-sm': [
          '12px',
          { lineHeight: '1', letterSpacing: '0', fontWeight: '500' },
        ],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
